git rm --cached ./CI/eco_protection/log.dat        
git rm --cached ./CI/eco_protection/__log.dat 
git rm --cached ./ML/adder/classifiers/adder_00704.dat 
git rm --cached ./ML/adder/mnist_cnn_raw.dat 
git rm --cached ./ML/auto_game/double11/ban.dat 
git rm --cached ./ML/auto_game/double11/list.dat 
git rm --cached ./ML/Bool_fun_est/datas.dat 
git rm --cached ./ML/Bool_fun_est/iterate.dat 
git rm --cached ./ML/China_daily/china_daily.dat 
git rm --cached ./ML/China_daily/shrinked_200_3.dat 
git rm --cached ./ML/China_daily/shrinked_200_4.dat 
git rm --cached ./ML/China_daily/stoplist.dat 
git rm --cached ./ML/China_daily/test.dat 
git rm --cached ./ML/co-evaluate/data.dat 
git rm --cached ./ML/guess_next/cls/077_10.dat 
git rm --cached ./ML/guess_next/cls/079.dat 
git rm --cached ./ML/guess_next/cls/088.dat 
git rm --cached ./ML/guess_next/cls/save.dat 
git rm --cached ./ML/guess_next/cls/wired.dat 
git rm --cached ./ML/guess_next/origin.dat 
git rm --cached ./ML/guess_next/save.dat 
git rm --cached ./ML/lines/line234.dat 
git rm --cached ./ML/lines/lines.dat 
git rm --cached ./ML/lottery/fast3/data_20140701001_2014103104.dat 
git rm --cached ./ML/most_act/mnist_cnn_raw.dat 
git rm --cached ./ML/tic-tac-toe/iterate.dat 
git rm --cached ./ML/_generative_nn/ann.dat 
git rm --cached ./ML/_generative_nn/mnist_cnn_raw.dat 
git rm --cached ./Proj/2048/self_learning/iterate.dat 
git rm --cached ./Proj/2048/test_with_f/iterate.dat
